name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: ls -la ./dist

      - name: Deploy 🚀 # 第三步：部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 部署的目录
          branch: gh-pages # 部署到哪个分支

